# Generated by Django 4.2.16 on 2025-01-02 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='status',
            field=models.CharField(choices=[('todo', 'To-Do'), ('in_progress', 'In Progress'), ('done', 'Done')], default='todo', max_length=50),
        ),
    ]
